DROP TABLE IF EXISTS MEASUREMENT;

CREATE TABLE MEASUREMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATE VARCHAR(250) NOT NULL,
    PM10 VARCHAR(250) NOT NULL,
    DESCRIPTION VARCHAR(250)
);

INSERT INTO MEASUREMENT(DATE, PM10, DESCRIPTION) VALUES
('28-05-2019', '12.0', 'OK - nice result');